package monte.test.spec.rest;

import io.restassured.response.Response;
import monte.test.core.model.api.PetRequest;
import monte.test.core.model.api.PetResponse;
import monte.test.core.utils.PetDataGenerator;
import monte.test.spec.rest.base.AbstractTest;
import org.testng.annotations.Test;

import static org.assertj.core.api.Assertions.assertThat;

public class UpdatePetTest extends AbstractTest {

    @Test
    public void testUpdatePet() {
        // Prepare request data
        PetRequest request = PetDataGenerator.randomPet();
        // Create a pet
        Response responseCreate = petApiClient.createPet(request);
        PetResponse createdPet = responseCreate
                .body()
                .as(PetResponse.class);

        String petId = createdPet.petId();

        // Update the pet
        PetRequest requestUpdatedPet = PetDataGenerator.randomPet();
        Response responseUpdate = petApiClient.updatePet(petId, requestUpdatedPet);

        // Asserting pet update
        assertThat(responseUpdate.statusCode())
                .isEqualTo(200);

        PetResponse updatedPet = responseUpdate
                .body()
                .as(PetResponse.class);

        assertThat(updatedPet)
                .isNotNull()
                .usingRecursiveComparison()
                .ignoringFields("id", "petId") // fields generated by server
                .isEqualTo(requestUpdatedPet);
    }
}
